// Copyright 2026 Columnar Technologies Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"crypto/sha256"
	"fmt"
	"io"
	"net/url"
	"os"
	"strings"

	"github.com/Masterminds/semver/v3"
	"github.com/columnar-tech/dbc/internal/resolution"
	"github.com/pelletier/go-toml/v2"
)

const (
	lockFileVersionV1 = 1
	lockFileVersion   = 2
)

// LockFile is the normalized in-memory form of supported lockfile versions.
// Version 1 entries are retained as legacy library proofs until a source has
// resolved the corresponding archive metadata.
type LockFile struct {
	Version  int        `toml:"version" comment:"This file is automatically @generated by dbc. Not intended for manual editing"`
	Revision int        `toml:"revision"`
	Drivers  []lockInfo `toml:"drivers"`

	lockinfo map[string]lockInfo `toml:"-"`
}

type lockInfo struct {
	Name      string              `toml:"name"`
	Version   *semver.Version     `toml:"version"`
	Source    lockSource          `toml:"source"`
	Evidence  lockEvidence        `toml:"evidence,omitempty"`
	Artifacts []lockArtifact      `toml:"artifacts,omitempty"`
	Legacy    *legacyLibraryProof `toml:"legacy,omitempty"`
	// These fields are transient adapters for the current sync pipeline. They
	// are populated only while reading a v1 lock and are never serialized.
	Platform string `toml:"-"`
	Checksum string `toml:"-"`
}

type lockSource struct {
	Type    string `toml:"type"`
	Project string `toml:"project,omitempty"`
	URL     string `toml:"url,omitempty"`
	Path    string `toml:"path,omitempty"`
}

type lockEvidence struct {
	BundleURL       string `toml:"bundle_url,omitempty"`
	BundleHash      string `toml:"bundle_hash,omitempty"`
	ReleaseListURL  string `toml:"release_list_url,omitempty"`
	ReleaseListHash string `toml:"release_list_hash,omitempty"`
}

type lockArtifact struct {
	Platform         string               `toml:"platform,omitempty"`
	OS               string               `toml:"os,omitempty"`
	Arch             string               `toml:"arch,omitempty"`
	LibC             string               `toml:"libc,omitempty"`
	Variant          string               `toml:"variant,omitempty"`
	Format           string               `toml:"format,omitempty"`
	URL              string               `toml:"url,omitempty"`
	Path             string               `toml:"path,omitempty"`
	Hash             string               `toml:"hash"`
	Size             *int64               `toml:"size"`
	HostRequirements lockHostRequirements `toml:"host_requirements,omitempty"`
}

type lockHostRequirements struct {
	OSMin    string                 `toml:"os_min,omitempty"`
	GLibCMin string                 `toml:"glibc_min,omitempty"`
	Libs     []string               `toml:"libs,omitempty"`
	Bins     []lockNamedRequirement `toml:"bins,omitempty"`
}

type lockNamedRequirement struct {
	Name string `toml:"name"`
	Min  string `toml:"min,omitempty"`
}

// legacyLibraryProof is deliberately distinct from lockArtifact.Hash: v1
// stored the hash of the installed shared library, not the archive.
type legacyLibraryProof struct {
	Platform    string `toml:"platform"`
	LibraryHash string `toml:"library_hash"`
}

type lockFileHeader struct {
	Version *int `toml:"version"`
}

type lockFileV1 struct {
	Version int            `toml:"version"`
	Drivers []lockDriverV1 `toml:"drivers"`
}

type lockDriverV1 struct {
	Name     string          `toml:"name"`
	Version  *semver.Version `toml:"version"`
	Platform string          `toml:"platform,omitempty"`
	Checksum string          `toml:"checksum,omitempty"`
}

type lockFileV2 LockFile

func loadLockFile(p string) (LockFile, error) {
	var lf LockFile
	data, err := os.ReadFile(p)
	if err != nil {
		return lf, fmt.Errorf("error opening lock file %s: %w", p, err)
	}

	var header lockFileHeader
	if err := toml.Unmarshal(data, &header); err != nil {
		return lf, fmt.Errorf("error decoding lock file %s: %w", p, err)
	}
	if header.Version == nil {
		return lf, fmt.Errorf("error decoding lock file %s: missing version", p)
	}

	switch *header.Version {
	case lockFileVersionV1:
		var wire lockFileV1
		if err := toml.Unmarshal(data, &wire); err != nil {
			return lf, fmt.Errorf("error decoding lock file %s: %w", p, err)
		}
		lf, err = normalizeLockFileV1(wire)
		if err != nil {
			return LockFile{}, fmt.Errorf("invalid lock file %s: %w", p, err)
		}
	case lockFileVersion:
		var wire lockFileV2
		if err := toml.Unmarshal(data, &wire); err != nil {
			return lf, fmt.Errorf("error decoding lock file %s: %w", p, err)
		}
		lf = LockFile(wire)
		if err := validateLockFileV2(lf); err != nil {
			return LockFile{}, fmt.Errorf("invalid lock file %s: %w", p, err)
		}
	default:
		return lf, fmt.Errorf("unsupported lock file version %d", *header.Version)
	}

	lf.indexDrivers()
	return lf, nil
}

func normalizeLockFileV1(wire lockFileV1) (LockFile, error) {
	lf := LockFile{Version: lockFileVersionV1}
	seenNames := make(map[string]struct{}, len(wire.Drivers))
	for i, old := range wire.Drivers {
		if old.Name == "" {
			return LockFile{}, fmt.Errorf("driver %d has no name", i)
		}
		if _, exists := seenNames[old.Name]; exists {
			return LockFile{}, fmt.Errorf("duplicate driver %q", old.Name)
		}
		seenNames[old.Name] = struct{}{}
		if old.Version == nil {
			return LockFile{}, fmt.Errorf("driver %q has no version", old.Name)
		}
		driver := lockInfo{Name: old.Name, Version: old.Version}
		if (old.Platform == "") != (old.Checksum == "") {
			return LockFile{}, fmt.Errorf("driver %d must have both platform and checksum or neither", i)
		}
		if old.Platform != "" && old.Checksum != "" {
			if err := validateLegacyLibraryHash(old.Checksum); err != nil {
				return LockFile{}, fmt.Errorf("driver %q has invalid v1 checksum: %w", old.Name, err)
			}
			driver.Legacy = &legacyLibraryProof{Platform: old.Platform, LibraryHash: old.Checksum}
			driver.Platform = old.Platform
			driver.Checksum = old.Checksum
		}
		lf.Drivers = append(lf.Drivers, driver)
	}
	return lf, nil
}

func (d lockInfo) legacyChecksumFor(platform string) string {
	if d.Legacy == nil || d.Legacy.Platform != platform {
		return ""
	}
	return d.Legacy.LibraryHash
}

func (lf *LockFile) indexDrivers() {
	lf.lockinfo = make(map[string]lockInfo, len(lf.Drivers))
	for _, driver := range lf.Drivers {
		lf.lockinfo[driver.Name] = driver
	}
}

func validateLockFileV2(lf LockFile) error {
	if lf.Version != lockFileVersion {
		return fmt.Errorf("expected lock file version %d, got %d", lockFileVersion, lf.Version)
	}
	if lf.Revision < 0 {
		return fmt.Errorf("lock file revision must not be negative")
	}
	seenDrivers := make(map[string]struct{}, len(lf.Drivers))
	for i, driver := range lf.Drivers {
		if driver.Name == "" {
			return fmt.Errorf("driver %d has no name", i)
		}
		if _, exists := seenDrivers[driver.Name]; exists {
			return fmt.Errorf("duplicate driver %q", driver.Name)
		}
		seenDrivers[driver.Name] = struct{}{}
		if driver.Version == nil {
			return fmt.Errorf("driver %q has no version", driver.Name)
		}
		if err := validateLockInfo(driver); err != nil {
			return fmt.Errorf("driver %q: %w", driver.Name, err)
		}
	}
	return nil
}

func validateLockSource(source lockSource) error {
	if source.Type == "" {
		return fmt.Errorf("missing type")
	}
	switch source.Type {
	case "packslip":
		if source.Project == "" {
			return fmt.Errorf("packslip source has no project")
		}
		if source.URL != "" || source.Path != "" {
			return fmt.Errorf("packslip source contains fields for another source type")
		}
	case "registry":
		if source.URL == "" {
			return fmt.Errorf("registry source has no URL")
		}
		if err := validateHTTPURL("registry source URL", source.URL); err != nil {
			return err
		}
		if source.Project != "" || source.Path != "" {
			return fmt.Errorf("registry source contains fields for another source type")
		}
	case "path":
		if source.Path == "" {
			return fmt.Errorf("path source has no path")
		}
		if source.Project != "" || source.URL != "" {
			return fmt.Errorf("path source contains fields for another source type")
		}
	default:
		return fmt.Errorf("unsupported source type %q", source.Type)
	}
	return nil
}

func validateHTTPURL(field, raw string) error {
	parsed, err := url.Parse(raw)
	if err != nil || !parsed.IsAbs() ||
		(!strings.EqualFold(parsed.Scheme, "http") && !strings.EqualFold(parsed.Scheme, "https")) || parsed.Hostname() == "" {
		return fmt.Errorf("%s must be an absolute HTTP(S) URL with a host", field)
	}
	return nil
}

func validateLockArtifacts(artifacts []lockArtifact) error {
	seenSelectors := make(map[string]struct{}, len(artifacts))
	seenURLs := make(map[string]struct{}, len(artifacts))
	for i, artifact := range artifacts {
		if artifact.Platform == "" && (artifact.OS == "" || artifact.Arch == "") {
			return fmt.Errorf("artifact %d must identify a platform or both OS and architecture", i)
		}
		if (artifact.OS == "") != (artifact.Arch == "") {
			return fmt.Errorf("artifact %d must provide OS and architecture together", i)
		}
		if (artifact.URL == "") == (artifact.Path == "") {
			return fmt.Errorf("artifact %d must have exactly one of URL or path", i)
		}
		if artifact.Hash == "" || artifact.Size == nil {
			return fmt.Errorf("artifact %d must have a finalized hash and size", i)
		}
		if err := validateLockHash(artifact.Hash); err != nil {
			return fmt.Errorf("artifact %d: %w", i, err)
		}
		if *artifact.Size < 0 {
			return fmt.Errorf("artifact %d has negative size", i)
		}
		if artifact.URL != "" {
			if err := validateHTTPURL("artifact URL", artifact.URL); err != nil {
				return fmt.Errorf("artifact %d: %w", i, err)
			}
		}
		selector := artifactSelectorIdentity(artifact)
		if _, exists := seenSelectors[selector]; exists {
			return fmt.Errorf("duplicate or ambiguous artifact selector %q", selector)
		}
		seenSelectors[selector] = struct{}{}
		location := artifact.URL
		if artifact.Path != "" {
			location = "path:" + artifact.Path
		}
		if _, exists := seenURLs[location]; exists {
			return fmt.Errorf("duplicate artifact location %q", location)
		}
		seenURLs[location] = struct{}{}
	}
	return nil
}

func validateLockHash(hash string) error {
	// Share the resolution layer's canonical digest contract.
	return resolution.ValidateArtifactMetadata(hash, nil)
}

func artifactSelectorIdentity(artifact lockArtifact) string {
	osName, arch, libc, variant := artifact.OS, artifact.Arch, artifact.LibC, artifact.Variant
	if platformOS, platformArch, platformLibC, platformVariant, ok := parsePlatformTuple(artifact.Platform); ok {
		if osName == "" {
			osName = platformOS
		}
		if arch == "" {
			arch = platformArch
		}
		if libc == "" {
			libc = platformLibC
		}
		if variant == "" {
			variant = platformVariant
		}
	}
	if osName == "linux" && libc == "" {
		libc = "gnu"
	}
	return fmt.Sprintf("%s\x00%s\x00%s\x00%s", osName, arch, libc, variant)
}

func parsePlatformTuple(platform string) (osName, arch, libc, variant string, ok bool) {
	if platform == "" {
		return "", "", "", "", false
	}
	parts := strings.Split(platform, "_")
	if len(parts) < 2 {
		return "", "", "", "", false
	}
	osName, arch = parts[0], parts[1]
	for _, part := range parts[2:] {
		switch part {
		case "gnu", "musl":
			libc = part
		default:
			if variant == "" {
				variant = part
			} else {
				variant += "_" + part
			}
		}
	}
	return osName, arch, libc, variant, true
}

func validateLegacyLibraryHash(hash string) error {
	if len(hash) != 64 {
		return fmt.Errorf("installed-library checksum must contain 64 lowercase hexadecimal characters")
	}
	for _, ch := range hash {
		if (ch < '0' || ch > '9') && (ch < 'a' || ch > 'f') {
			return fmt.Errorf("installed-library checksum must contain 64 lowercase hexadecimal characters")
		}
	}
	return nil
}

func checksum(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("error opening file %s for checksum: %w", path, err)
	}
	defer f.Close()
	return checksumFile(f, path)
}

func checksumFile(file *os.File, path string) (string, error) {
	if _, err := file.Seek(0, io.SeekStart); err != nil {
		return "", fmt.Errorf("error seeking file %s for checksum: %w", path, err)
	}
	h := sha256.New()
	if _, err := io.Copy(h, file); err != nil {
		return "", fmt.Errorf("error calculating checksum for file %s: %w", path, err)
	}
	if _, err := file.Seek(0, io.SeekStart); err != nil {
		return "", fmt.Errorf("error rewinding file %s after checksum: %w", path, err)
	}

	return fmt.Sprintf("%x", h.Sum(nil)), nil
}
