// Copyright 2025 Columnar Technologies Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"crypto/sha256"
	"fmt"
	"io"
	"os"

	"github.com/Masterminds/semver/v3"
	"github.com/pelletier/go-toml/v2"
)

const lockFileVersion = 1

type lockInfo struct {
	Name     string          `toml:"name"`
	Version  *semver.Version `toml:"version"`
	Platform string          `toml:"platform,omitempty"`
	Checksum string          `toml:"checksum,omitempty"`
}

type LockFile struct {
	Version int        `toml:"version" comment:"This file is automatically @generated by dbc. Not intended for manual editing"`
	Drivers []lockInfo `toml:"drivers"`

	lockinfo map[string]lockInfo `toml:"-"`
}

func loadLockFile(p string) (LockFile, error) {
	var lf LockFile
	f, err := os.Open(p)
	if err != nil {
		return lf, fmt.Errorf("error opening lock file %s: %w", p, err)
	}
	defer f.Close()

	if err := toml.NewDecoder(f).Decode(&lf); err != nil {
		return lf, fmt.Errorf("error decoding lock file %s: %w", p, err)
	}

	lf.lockinfo = make(map[string]lockInfo)
	for _, d := range lf.Drivers {
		lf.lockinfo[d.Name] = d
	}

	return lf, nil
}

func checksum(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("error opening file %s for checksum: %w", path, err)
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", fmt.Errorf("error calculating checksum for file %s: %w", path, err)
	}

	return fmt.Sprintf("%x", h.Sum(nil)), nil
}
