repos:
  - repo: https://github.com/amoeba/license-header-check
    rev: v0.1
    hooks:
      - id: license-header-check
        args:
          - "--template"
          - >-
            Copyright \(c\) [YEAR] Columnar Technologies Inc\.  All rights reserved\.
