# Copyright (c) 2025 Columnar Technologies Inc.  All rights reserved.

repos:
  - repo: https://github.com/amoeba/license-header-check
    rev: v0.1
    hooks:
      - id: license-header-check
        args:
          - "--template"
          - >-
            Copyright \(c\) [YEAR] Columnar Technologies Inc\.  All rights reserved\.
          - "--max_lines"
          - "2"
        exclude: |
          (?x)^(
              .*\.svg|
              columnar\.pubkey|
              scripts/install\.(ps1|sh)|
              LICENSE|
              go\.sum|
              pixi\.lock|
              resources/dbc\.wxs
          )$
