name = "FlightSQL ADBC Driver"
publisher = "arrow-adbc"
license = "Apache-2.0"
version = "v1.6.0"
source = "dbc"

[ADBC]
version = "v1.1.0"

[ADBC.features]
supported = [ "bulk insert", "prepared statement" ]
unsupported = [ "async" ]

[Driver]
shared = "/home/zeroshade/local/lib/libadbc_driver_flightsql.so"
