# Copyright (c) 2025 Columnar Technologies.  All rights reserved.

name: Go
on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: 1.24.2
          cache: true
          cache-dependency-path: go.sum
      - name: Build dbc
        run: go build ./cmd/dbc
      - name: Run Tests
        run: go test -v ./...
